POST http://localhost:5243/Accounts
Content-Type: application/json

{
    "Username": "Tamer",
    "Password": "12345678"
}

###
POST http://localhost:5243/companies
Content-Type: application/json

{
    "CompanyName": "TamerCO",
    "AccountId": 1
}



